name: Test

on:
  push

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./test

    steps:
    - uses: actions/checkout@v4

    name: Run tests
      php test_runner.php
